18F/charlie-slack-bot-facts

- dags.json
> Add Fox facts

- dags.json
Incorporates manual facts from #12. Closes #12. (We can create a new manual dag fact issue later!)
> Update dags.json with manual facts

- ed.json
will add some more later as i can
> adding a few choice sayings/actions

- ed.json
cuz if ed simulator is going to be any good at being like ed, it also has to be good at listening, not just talking
> adding a new fact

- dags.json
> Adds Teddy dag fact

- dags.json
> Revert "A temporary PR"

- dags.json
> Added Sidney dag facts

- dags.json
Adding hudson dog to the list!
> added Hudsy

- README.md
- a11y-facts.json
PR to update Charlie: https://github.com/18F/charlie/pull/302
> A11y facts

- .github/workflows/validate.yml
After this is merged (or maybe when this one is created, we'll see!), new pull requests will merge automatically after the tests pass.
> Turn on automatic merging for each pull request

- .github/ISSUE_TEMPLATE/add_fact.yml
This will eventually be coupled with a GitHub action that will turn the issue into a code change. :magic:
> Add an issue template for creating new facts

- .github/workflows/addFact.js
- .github/workflows/issues.yml
- .github/workflows/validate.yml
- package-lock.json
- package.json
I don't expect this to quite work, but there's no way to know without actually putting it into a live action.
> Automatically create facts from properly-formatted issues

- dags.json
This fact is being added automatically from the contents of #113
> Adding fact for #113

- dags.json
This fact is being added automatically from the contents of #128
> Adding fact for #128

- dags.json
This fact is being added automatically from the contents of #130
> Adding fact for #130

- dags.json
This fact is being added automatically from the contents of #146
> Adding fact for #146

- dags.json
This fact is being added automatically from the contents of #148
> Adding fact for #148

- dags.json
This fact is being added automatically from the contents of #153
> Adding fact for #153

- dag-intros.json
> Update with a Ruby intro.json

- dag-intros.json
Hopefully the image link will work...
> Added a Ripley intro!

- dag-intros.json
This fact is being added automatically from the contents of #166
> Adding fact for #166

- cat-intros.json
Add cat-intros.json along with two super great intros for two super great cats
> Add initial cat intros file

- cat-intros.json
This fact is being added automatically from the contents of #185
> Adding fact for #185

- dags.json
This fact is being added automatically from the contents of #200
> Adding fact for #200

- giraffes.json
This fact is being added automatically from the contents of #204
> Adding fact for #204

- dags-alumni.json
- dags.json
@micahsaul is back so Bubba is no longer an alumni again.
> Unretire Bubba!

- hyraxes.json
all this talk of giraffes and capybaras got me thinking about hyraxes
> add hyrax facts

- dags.json
adding a Ruby fact about her water-drinking behavior
> Ruby's water

- giraffes.json
This fact is being added automatically from the contents of #219
> Adding fact for #219

- .github/workflows/validate.yml
- updated to use a newer version of the org membership check action
- added an additional check to allow auto-merging dependabot PRs
> Update the auto-approve workflow

- capybaras.json
Added two important capybara facts
> Important new capybara facts

- birds.json
- pets.json
That was a holdover from when bird facts were in with the dags.
> Removing "(bird)"

- giraffes.json
This fact is being added automatically from the contents of #231
> Adding fact for #231

- giraffes.json
> Use a different homonym

- .github/workflows/addFact.js
There were a few rapid-fire, small PRs in a row to fix an issue with PRs not being automatically merged. _This_ PR is to cleanup some of the leftover cruft from those, and it should bring this campaign of fixing automations to a close. 😄
> Clean up a bit

- cat-intros-alumni.json
- cat-intros.json
add alumni cats, promote Theodosius and Rorschach to alumni status
> add alumni cats, promote Theodosius and Rorschach to alumni status

- dags.json
- pets.json
Adds 2 Rory facts with pictures
> Adds 2 Rory facts
